apiVersion: v1
kind: Pod
metadata:
  name: busypod
  namespace: mrp
spec:
  containers:
    - name: busy
      image: busybox
      command: 
        - "/bin/tail"
        - "-f"
        - "/proc/cpuinfo"
