apiVersion: v1
kind: Service
metadata:
  name: "front"
  namespace: mrp
  labels:
    app: "front"
spec:
  selector: 
    app: "front"
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "front"
  namespace: mrp
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "front"
    spec:
      containers:
      - name: "front"
        image: index.docker.io/tsuyoshiushio/puweb:${BUILD_BUILDID}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 30
          periodSeconds: 30
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 30
          periodSeconds: 30
          failureThreshold: 10          
      imagePullSecrets:
        - name: mydockerhubkey
